### ISSUE TITLE
Authentication hash is case sensitive?

### ISSUE THREAD

**Issue by dalee-bis** [NHSDigital/mesh-sandbox#131]
I'm not sure if this is by design, but the HMAC hash seems to be case-sensitive in the sandbox. I don't know if this is also the case in the integration and production APIs. It doesn't seem to be mentioned at https://digital.nhs.uk/developer/api-catalogue/message-exchange-for-social-care-and-health-api#overview--mesh-authorization-header

I discovered this because the C# implementation of `Convert.ToHexString()` generates the hexadecimal in uppercase. The python implementation of `hexdigest()` seems to generate the hash in lowercase. This causes the following line to fail:

https://github.com/NHSDigital/mesh-sandbox/blob/6da4c2c88a2ab759016ea1d0496adceadaa2c275/src/mesh_sandbox/common/messaging.py#L363-L373

It would be good to either have this documented, or have the implementation be consistently case-insensitive.

**Comment by johnwilliams57-nhs** [comment]
I spoke with the other devs on the MESH team and we think this comparison should be case insensitive.

I've raised the following pull request for sandbox:
https://github.com/NHSDigital/mesh-sandbox/pull/142

We can't merge it until the same change i've made in the mesh api is released.

i'll update here again once it's merged.

**Comment by johnwilliams57-nhs** [comment]
this has now been merged in and is in v1.0.22.

Thanks very much for highlighting this.
